ALTER TABLE movies
ADD COLUMN lecteur_links VARCHAR(255),
ADD COLUMN descr TEXT,
ADD COLUMN categories VARCHAR(255),
ADD COLUMN poster VARCHAR(255),
ADD COLUMN sortie DATE,
ADD COLUMN director VARCHAR(255),
ADD COLUMN casts VARCHAR(255),
ADD COLUMN movie_time INT,
ADD COLUMN ratings DECIMAL(3,1);